### ISSUE TITLE
Набрать 100 рейтинга на acmp

### ISSUE THREAD

**Issue by ShiverAwe** [ShiverAwe/UPSTUDY#1]
- [x] Решить задач на acmp на 100 баллов суммарно

- [x] Скриншот профиля с рейтином и списком задач добавить в комментарии к этому заданию

**Comment by Andr3vv** [comment]
![image](https://user-images.githubusercontent.com/34164298/33851319-a93baaa4-dec7-11e7-8beb-32237b7713d4.png)
